 [[redirects]]
  from = "/*"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}