 [[redirects]]
  from = "/*"
  to = "https://mellow-luxurious-cotija.glitch.me/searchForCity/"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "https://mellow-luxurious-cotija.glitch.me/searchForCity/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}